### ISSUE TITLE
docker-compose setup - external apps

### ISSUE THREAD

**Issue by vid** [cloud-py-api/docker-socket-proxy#20]
I have to admit this seemed overly complex, but I think an api is a great idea. I think I got it working. In case it helps anyone, here's what I used for docker compose:

```
  docker-socket-proxy:
    container_name:  nextcloud-appapi-dsp
    image: ghcr.io/cloud-py-api/nextcloud-appapi-dsp:release
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - container_proxy # this is the same local network that I use for other containers
    environment:
       NC_HAPROXY_PASSWORD: "xxx"
```

Here's the config in nextcloud:

```
Name: docker_socket_proxy
Protocol: http
Host: nextcloud-appapi-dsp:2375
Deploy config
Docker network: container_proxy
Nextcloud URL: <my nextcloud url>
HaProxy password: xxx
GPUs support: true
```

I was experiencing "Default Deploy daemon is not accessible" until I got it working. However, for some reason once this is set up, external apps don't list. Is there a solution for this?

**Comment by andrey18106** [comment]
Hi!

Could you clarify please, where there is no list of ExApps? This problem is not related to the Deploy daemon, as the list of ExApps is loaded from AppStore (https://apps.nextcloud.com/api/v1/appapi_apps.json) and cached on the Nextcloud side in `/data/appdata_<instanceid>/appstore/appapi_apps.json` folder.

**Comment by vid** [comment]
Thanks for that information. I think it was unfamiliarity since I am new to all this. Once I resolved the error, I see apps when selecting categories. However, they fail to install with "An error occurred during the request. Unable to proceed." 

I have just ordered an RTX GPU so am CPU only right now, but from what I can tell some of these functions should work. Maybe you could have a teleworkshop for all this? There's a lot but I'd love to know more and perhaps contribute.

**Comment by bigcat88** [comment]
> However, they fail to install with "An error occurred during the request. Unable to proceed."

can you please show some logs regarding this?

Apps should install even with CPU only, maybe this is some bug in AppAPI

**Comment by vid** [comment]
Sorry to ask this, but where I would I find those specific logs? I've searched the container and don't see anything likely. /var/log/apache2 logs are linked to stdout/stderr.  I just did Deploy and Enable TalkbotAPI Example, via docker logs I can see the http requests but no sign of errors. I just get that notification and eventually it reverse to uninstalled.

**Comment by bigcat88** [comment]
Looks like some config problem. We currently work right now on this:

https://github.com/cloud-py-api/app_api/issues/174

and hopefully this will be included in release after next(so next AppAPI release is on this week) and "Test Deploy" button will be included in the AppAPI release at the end of April/start of May.

Can we wait that button to appear to faster diagnose the problems with configs? =)

**Comment by vid** [comment]
Yes, that looks very helpful. I am putting together a demo for a government group which is evaluating Nextcloud, AppAPI & localAI, so I will be excited to get this working.

**Comment by bigcat88** [comment]
> Yes, that looks very helpful. I am putting together a demo for a government group which is evaluating Nextcloud, AppAPI & localAI, so I will be excited to get this working.

if it is urgent, we can try determine where the problem is without that "Test deploy" button.

For example you can first try installing "To Gif" app and let's see if install successes and it works.
After that we can switch to ContextChat or whatever..
_or wait for 7-10 days_

**Comment by vid** [comment]
1. Nextcloud is running in a container.  docker-compose is below.
2. I can't ping nc_app_to_gif_example. I can ping eg nextcloud-db and the host works well otherwise
3. nextcloud is using a signed certificate (this is all running behind traefik with auto certs).
4. Yes, I can ping "nextcloud" from "nextcloud-appapi-dsp." 


```
version: '3.7'
 
services:
  db:
    image: mariadb:latest
    container_name: nextcloud-db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - container_proxy
    restart: unless-stopped
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: nextcloud
  
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    networks:
      - container_proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/redis:/var/lib/redis
 
  nextcloud:
    depends_on:
      - redis
      - db
      - docker-socket-proxy
    image: nextcloud
    environment:
      PUID: 1000
      PGID: 1000
      REDIS_HOST: redis
      MYSQL_HOST: db:3306
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: root
      MYSQL_PASSWORD: xxx
      MAINTENANCE_WINDOW_START: 3
      TRUSTED_PROXIES: "192.168.208.0/24"
      OVERWRITEHOST: "<hostname>" 
      OVERWRITEPROTOCOL: "https"
#      OVERWRITEWEBROOT SET the absolute web path of the proxy to the Nextcloud folder.
#      OVERWRITECONDADDR OVerwrite the values dependent on the remote address. The value must be a regular expression of the IP addresses of the proxy. This is useful when you use a reverse SSL proxy only for https access and you want to use the automatic detection for http access.
      OVERWRITE.CLI.URL: <hostname>/ # THe base URL for any URLs which are generated within Nextcloud using any kind of command line tools.

    container_name: nextcloud
    volumes:
      - /home/vid/D/ai/models/llama-2-7b-chat.Q4_K_M.gguf:/var/www/html/custom_apps/llm/src-py/models/llama-2-7b-chat.Q4_K_M.gguf
      - /home/vid/D/ai/models/whisper-medium:/var/www/html/custom_apps/stt_whisper/models/medium
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/data:/var/www/html/data
      - ./volumes/config:/var/www/html/config
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    networks:
      - container_proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud-secure.rule=Host(`<hostname>`)"
      - "traefik.http.routers.nextcloud-secure.tls=true"
      - "traefik.http.routers.nextcloud-secure.tls.certresolver=production"
      - "traefik.http.routers.nextcloud-secure.service=nextcloud-service"
      - "traefik.http.services.nextcloud-service.loadbalancer.server.port=80"
      - "traefik.docker.network=container_proxy"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud_redirectregex"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.regex=https://(.*)/.well-known/(?:card|cal)dav"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.replacement=https://$${1}/remote.php/dav"
      - "traefik.http.routers.nextcloud-secure.middlewares=nextcloud_redirectregex@docker"
      - "traefik.http.middlewares.nextcloud-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.nextcloud-secure.middlewares=nextcloud-headers@docker,nextcloud_redirectregex@docker"
      - "traefik.http.routers.nextcloud.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.middlewares.nextcloud-headers.headers.customRequestHeaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.nextcloud-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.nextcloud-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.nextcloud-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nextcloud-headers.headers.stsSeconds=15552000"

  docker-socket-proxy:
    container_name:  nextcloud-appapi-dsp
    image: ghcr.io/cloud-py-api/nextcloud-appapi-dsp:release
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - container_proxy
    environment:
       NC_HAPROXY_PASSWORD: "yyy"

networks:
  container_proxy:
    external: true

```

Unfortunately, I restarted the container and my apps directory was reset, I don't see the external apps list anymore. I am a bit lost about preventing this from happening. I will mount apps on a volume to see if that helps, none of the guidance I saw talked about this.

**Comment by bigcat88** [comment]
Most such issues come from that situation usually where ExApp can not talk to Nextcloud.
Reason are usually is an incorrect Nextcloud Url(we can not detect it correctly for some situations in AppAPI to fill).
Usually helps using `http` instead of `https`, or changing url to point to reverse proxy address if changing "https"->"http" does not help.

**Comment by vid** [comment]
It does pass "verify connection," though. Is that not comprehensive?
Probably unrelated, but I reinstalled, am back where I was before, but now it says `GPUs support: false`

**Comment by andrey18106** [comment]
@vid Hi! AppAPI 2.5.1 released, as soon as you receive an update, you can use "Test Deploy" button on Deploy daemon to check which step fails (https://cloud-py-api.github.io/app_api/TestDeploy.html).

**Comment by vid** [comment]
Thanks! Can't wait to try, I hope it works.

**Comment by vid** [comment]
OK! I got the update. For some reason, the check gets stuck on Image pull.

![image](https://github.com/cloud-py-api/docker-socket-proxy/assets/68174/41f9bb03-e35f-4fbf-a528-7c1b0c779180)
I notice a few other external apps are also stuck:


![image](https://github.com/cloud-py-api/docker-socket-proxy/assets/68174/f7279fe9-d1b5-4355-b223-b3bd025210b7)

I have done docker compose down and up, but they stick around. Any advice to correct this?

**Comment by andrey18106** [comment]
The Test Deploy ExApp has different images for CPU (1.3GB)/GPU (8.3GB) hardware support, may take some time to download. But in your case it seems it got stuck due to some error in code, that we could fix in AppAPI.
Is there any error logs in Nextcloud from app_api?

**Comment by vid** [comment]
I think it's "stuck," I haven't tried to install the external apps for a few days, they're just not updating from "deploying." And "image pull" for the AppAPI test goes right to 76%.

I'm still finding my way around, but I don't see anything from today with grep -i appapi data/nextcloud.log. Is there somewhere else I can look?

I see these from a few days ago;

{"reqId":"EDdS5k6U5JhAdD4sN9Jr","level":0,"time":"2024-04-29T18:38:19+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"app_api\" in appstore","userAgent":"--","version":"28.0.4.1","data":{"app":"updater"}}
{"reqId":"EDdS5k6U5JhAdD4sN9Jr","level":0,"time":"2024-04-29T18:38:19+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"app_api\" in appstore","userAgent":"--","version":"28.0.4.1","data":{"app":"updater"}}
{"reqId":"CzexqZ18xp7YGrsIwati","level":3,"time":"2024-04-29T19:00:05+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined array key \"computeDevice\" at /var/www/html/custom_apps/app_api/lib/DeployActions/DockerActions.php#462","userAgent":"--","version":"29.0.0.19","data":{"app":"PHP"}}
{"reqId":"CzexqZ18xp7YGrsIwati","level":3,"time":"2024-04-29T19:00:05+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Trying to access array offset on value of type null at /var/www/html/custom_apps/app_api/lib/DeployActions/DockerActions.php#462","userAgent":"--","version":"29.0.0.19","data":{"app":"PHP"}}
{"reqId":"1v4ICdcOOxgLNCK1ZLmf","level":3,"time":"2024-04-29T19:00:16+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined array key \"computeDevice\" at /var/www/html/custom_apps/app_api/lib/DeployActions/DockerActions.php#462","userAgent":"--","version":"29.0.0.19","data":{"app":"PHP"}}
{"reqId":"1v4ICdcOOxgLNCK1ZLmf","level":3,"time":"2024-04-29T19:00:16+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Trying to access array offset on value of type null at /var/www/html/custom_apps/app_api/lib/DeployActions/DockerActions.php#462","userAgent":"--","version":"29.0.0.19","data":{"app":"PHP"}}
{"reqId":"gHzNYx8Aj3XTGV0Rythv","level":3,"time":"2024-04-29T19:04:51+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined array key \"computeDevice\" at /var/www/html/custom_apps/app_api/lib/DeployActions/DockerActions.php#462","userAgent":"--","version":"29.0.0.19","data":{"app":"PHP"}}
{"reqId":"gHzNYx8Aj3XTGV0Rythv","level":3,"time":"2024-04-29T19:04:51+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Trying to access array offset on value of type null at /var/www/html/custom_apps/app_api/lib/DeployActions/DockerActions.php#462","userAgent":"--","version":"29.0.0.19","data":{"app":"PHP"}}
{"reqId":"gHzNYx8Aj3XTGV0Rythv","level":3,"time":"2024-04-29T19:04:52+00:00","remoteAddr":"","user":"--","app":"app_api","method":"","url":"--","message":"ExApp stt_whisper2 deployment failed. Error: Failed to pull image, GuzzleException occur: Server error: `POST http://nextcloud-appapi-dsp:2375/v1.41/images/create?fromImage=ghcr.io%2Fnextcloud%2Fstt_whisper2%3A1.1.2` resulted in a `500 Internal Server Error` response","userAgent":"--","version":"29.0.0.19","data":{"app":"app_api"}}
{"reqId":"vPWyghuJ83xFEhBqqESw","level":3,"time":"2024-04-29T19:05:00+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined array key \"computeDevice\" at /var/www/html/custom_apps/app_api/lib/DeployActions/DockerActions.php#462","userAgent":"--","version":"29.0.0.19","data":{"app":"PHP"}}
{"reqId":"vPWyghuJ83xFEhBqqESw","level":3,"time":"2024-04-29T19:05:00+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Trying to access array offset on value of type null at /var/www/html/custom_apps/app_api/lib/DeployActions/DockerActions.php#462","userAgent":"--","version":"29.0.0.19","data":{"app":"PHP"}}
{"reqId":"Zv8LVqYeTZvQogDojshh","level":3,"time":"2024-04-29T19:05:04+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined array key \"computeDevice\" at /var/www/html/custom_apps/app_api/lib/DeployActions/DockerActions.php#462","userAgent":"--","version":"29.0.0.19","data":{"app":"PHP"}}
{"reqId":"Zv8LVqYeTZvQogDojshh","level":3,"time":"2024-04-29T19:05:04+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Trying to access array offset on value of type null at /var/www/html/custom_apps/app_api/lib/DeployActions/DockerActions.php#462","userAgent":"--","version":"29.0.0.19","data":{"app":"PHP"}}
{"reqId":"Zv8LVqYeTZvQogDojshh","level":3,"time":"2024-04-29T19:05:04+00:00","remoteAddr":"","user":"--","app":"app_api","method":"","url":"--","message":"ExApp translate2 deployment failed. Error: Failed to pull image, GuzzleException occur: Server error: `POST http://nextcloud-appapi-dsp:2375/v1.41/images/create?fromImage=ghcr.io%2Fnextcloud%2Ftranslate2%3Alatest` resulted in a `500 Internal Server Error` response","userAgent":"--","version":"29.0.0.19","data":{"app":"app_api"}}
{"reqId":"x9VizBbzrpRDcMbY9Jt6","level":3,"time":"2024-04-29T19:08:04+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined array key \"computeDevice\" at /var/www/html/custom_apps/app_api/lib/DeployActions/DockerActions.php#462","userAgent":"--","version":"29.0.0.19","data":{"app":"PHP"}}
{"reqId":"x9VizBbzrpRDcMbY9Jt6","level":3,"time":"2024-04-29T19:08:04+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Trying to access array offset on value of type null at /var/www/html/custom_apps/app_api/lib/DeployActions/DockerActions.php#462","userAgent":"--","version":"29.0.0.19","data":{"app":"PHP"}}
{"reqId":"x9VizBbzrpRDcMbY9Jt6","level":3,"time":"2024-04-29T19:08:05+00:00","remoteAddr":"","user":"--","app":"app_api","method":"","url":"--","message":"ExApp stt_whisper2 deployment failed. Error: Failed to pull image, GuzzleException occur: Server error: `POST http://nextcloud-appapi-dsp:2375/v1.41/images/create?fromImage=ghcr.io%2Fnextcloud%2Fstt_whisper2%3A1.1.2` resulted in a `500 Internal Server Error` response","userAgent":"--","version":"29.0.0.19","data":{"app":"app_api"}}
{"reqId":"bfnDHiemxSQdUeTEX2aI","level":3,"time":"2024-04-29T19:08:37+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/custom_apps/app_api/lib/Command/ExApp/Register.php#154","userAgent":"--","version":"29.0.0.19","data":{"app":"PHP"}}
{"reqId":"bfnDHiemxSQdUeTEX2aI","level":3,"time":"2024-04-29T19:08:37+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/custom_apps/app_api/lib/Command/ExApp/Register.php#154","userAgent":"--","version":"29.0.0.19","data":{"app":"PHP"}}
{"reqId":"bfnDHiemxSQdUeTEX2aI","level":3,"time":"2024-04-29T19:08:37+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined array key \"computeDevice\" at /var/www/html/custom_apps/app_api/lib/DeployActions/DockerActions.php#462","userAgent":"--","version":"29.0.0.19","data":{"app":"PHP"}}
{"reqId":"bfnDHiemxSQdUeTEX2aI","level":3,"time":"2024-04-29T19:08:37+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Trying to access array offset on value of type null at /var/www/html/custom_apps/app_api/lib/DeployActions/DockerActions.php#462","userAgent":"--","version":"29.0.0.19","data":{"app":"PHP"}}
{"reqId":"6zOKSXHKk4MhXsdhcbQe","level":3,"time":"2024-04-29T19:08:42+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined array key \"computeDevice\" at /var/www/html/custom_apps/app_api/lib/DeployActions/DockerActions.php#462","userAgent":"--","version":"29.0.0.19","data":{"app":"PHP"}}
{"reqId":"6zOKSXHKk4MhXsdhcbQe","level":3,"time":"2024-04-29T19:08:42+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Trying to access array offset on value of type null at /var/www/html/custom_apps/app_api/lib/DeployActions/DockerActions.php#462","userAgent":"--","version":"29.0.0.19","data":{"app":"PHP"}}
{"reqId":"6zOKSXHKk4MhXsdhcbQe","level":3,"time":"2024-04-29T19:08:42+00:00","remoteAddr":"","user":"--","app":"app_api","method":"","url":"--","message":"ExApp stt_whisper2 deployment failed. Error: Failed to pull image, GuzzleException occur: Server error: `POST http://nextcloud-appapi-dsp:2375/v1.41/images/create?fromImage=ghcr.io%2Fnextcloud%2Fstt_whisper2%3A1.1.2` resulted in a `500 Internal Server Error` response","userAgent":"--","version":"29.0.0.19","data":{"app":"app_api"}}

**Comment by vid** [comment]
The `docker pull` works no problem in less than a minute. Is this what you mean by Deploy daemon configuration?

```
  docker-socket-proxy:
    restart: no
    container_name:  nextcloud-appapi-dsp
    image: ghcr.io/cloud-py-api/nextcloud-appapi-dsp:release
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - container_proxy
    environment:
       NC_HAPROXY_PASSWORD: "xxx"
````
